### ISSUE TITLE
Running into errors

### ISSUE THREAD

**Issue by Fredrik2002** [sanalsprasad/chessboard2fen#1]
Hi, I find your project very nice, but when I tried to run it with the sample data, I ran into this error : 

![image](https://github.com/sanalsprasad/chessboard2fen/assets/86866135/10b497e6-1faf-4497-a137-e0666fa01e60)

I tried to go in _piece_classifier.py_ line 14, I tried to replace `"model_weights"` by `"model_weights.index"`, but then I ran into this error :

![image](https://github.com/sanalsprasad/chessboard2fen/assets/86866135/1626b37f-e65a-41ff-9f69-d9c9a21393a5)

Any idea where this could be coming from ?

I'm on Windows 11 btw, python 3.11.4, tensorflow 2.14.0, keras 2.14.0

**Comment by sanalsprasad** [comment]
Hey Fredrik, Thanks for trying out the project, and sorry about the bug. I realized that some of the files associated with the saved model are missing. I will add them in a bit.

**Comment by sanalsprasad** [comment]
Hi Fredrik, Could you check if you are able to run the model now?

**Comment by Fredrik2002** [comment]
Hi, it works perfectly now, thank you very much ! Awesome project, I love it !
